/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author TLC
 */
public class THAO_TAC_TREN_JLIST extends javax.swing.JFrame {

    int a;

    DefaultListModel model = new DefaultListModel();

    ;
    /**
     * Creates new form THAO_TAC_TREN_JLIST
     */
    public THAO_TAC_TREN_JLIST() {
        initComponents();
        model.addElement(1);
        model.addElement(13);
        model.addElement(14);
        model.addElement(9);
        model.addElement(7);
        jList1.setModel(model);
        
    }

    public void kiemtra() {
        try {
            a = Integer.parseInt(tfNhap.getText());

        } catch (NumberFormatException e) {
            System.out.println(" lỗi");
            JOptionPane.showMessageDialog(null, "phải nhập vào 1 số");
            tfNhap.requestFocus();
            return;
        }
    }

    public void addList(int list) {

        try {
            jList1.setModel(model);
            model.addElement(list);
            tfNhap.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "vui lòng nhập số nguyên");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btNhap = new javax.swing.JButton();
        tfNhap = new javax.swing.JTextField();
        chSoAm = new javax.swing.JCheckBox();
        btThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btToSenSochan = new javax.swing.JButton();
        btSumList = new javax.swing.JButton();
        btXoaCacGiaTriToDen = new javax.swing.JButton();
        btBoToDen = new javax.swing.JButton();
        btToDenSoNguyenTo = new javax.swing.JButton();
        btToSenSoLe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("THAO TÁC TRÊN JLIST");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14), java.awt.Color.red)); // NOI18N
        jPanel1.setForeground(java.awt.Color.red);

        jScrollPane1.setViewportView(jList1);

        btNhap.setText("Nhập");
        btNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapActionPerformed(evt);
            }
        });

        chSoAm.setText("Cho Phép Nhập Số Âm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chSoAm)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNhap)
                    .addComponent(tfNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chSoAm))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỌN TÁC VỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N

        btToSenSochan.setText("Tô Đen Số Chẵn");
        btToSenSochan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToSenSochanActionPerformed(evt);
            }
        });

        btSumList.setText("Tổng giá Trị trong Jlist");
        btSumList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumListActionPerformed(evt);
            }
        });

        btXoaCacGiaTriToDen.setText("Xóa các giá trị đang tô đen");
        btXoaCacGiaTriToDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaCacGiaTriToDenActionPerformed(evt);
            }
        });

        btBoToDen.setText("Bỏ Tô Đen");
        btBoToDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoToDenActionPerformed(evt);
            }
        });

        btToDenSoNguyenTo.setText("Tô Đen Số Nguyên Tố");
        btToDenSoNguyenTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToDenSoNguyenToActionPerformed(evt);
            }
        });

        btToSenSoLe.setText("Tô Đen Số Lẻ");
        btToSenSoLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToSenSoLeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btBoToDen)
                        .addComponent(btXoaCacGiaTriToDen)
                        .addComponent(btSumList)
                        .addComponent(btToSenSoLe)
                        .addComponent(btToDenSoNguyenTo))
                    .addComponent(btToSenSochan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBoToDen, btSumList, btToDenSoNguyenTo, btToSenSoLe, btToSenSochan, btXoaCacGiaTriToDen});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btToSenSochan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btToSenSoLe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btToDenSoNguyenTo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBoToDen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btXoaCacGiaTriToDen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btSumList)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btBoToDen, btSumList, btToDenSoNguyenTo, btToSenSoLe, btToSenSochan, btXoaCacGiaTriToDen});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btThoat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapActionPerformed
        System.out.println(chSoAm.isSelected());
        int list;
        kiemtra();
        if (chSoAm.isSelected() == false) {
            if (a < 0) {
                JOptionPane.showMessageDialog(null, "để nhập số âm vui lòng tích vào nhập số âm");
                tfNhap.requestFocus();
                return;
            }else{
                 list = Integer.parseInt(tfNhap.getText());
                 addList(list);
            }

                          
            }else{
            list = Integer.parseInt(tfNhap.getText());
                 addList(list); 
        }
        
        System.out.println(jList1.getModel().getSize());

    }//GEN-LAST:event_btNhapActionPerformed
  
  
    private void btToSenSochanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToSenSochanActionPerformed
      ArrayList<Integer> arr = new ArrayList<Integer>();
        jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
//      int [] list=null; 
//      jList1.setSelectedIndices(list);
      for(int i=0;i<(jList1.getModel().getSize());i++){
         int temp=Integer.parseInt(model.get(i).toString());
         if(temp%2==0){
           arr.add(i);
           
         }
      }
     int [] list = new int [arr.size()];
      
      for(int i=0;i<arr.size();i++){
          list[i]=arr.get(i);
      }
//        System.out.println(model.size());
      jList1.setSelectedIndices(list);
    }//GEN-LAST:event_btToSenSochanActionPerformed

    private void btToSenSoLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToSenSoLeActionPerformed
           jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
       ArrayList<Integer> arr = new ArrayList<Integer>();
      
      for(int i=0;i<(jList1.getModel().getSize());i++){
         int temp=Integer.parseInt(model.get(i).toString());
         if(temp%2!=0){
           arr.add(i);
           
         }
      }
      int [] list = new int [arr.size()];
      
      for(int i=0;i<arr.size();i++){
          list[i]=arr.get(i);
      }
//        System.out.println(model.size());
      jList1.setSelectedIndices(list);
    }//GEN-LAST:event_btToSenSoLeActionPerformed

    private void btBoToDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoToDenActionPerformed
        jList1.removeSelectionInterval(0, model.size());
    }//GEN-LAST:event_btBoToDenActionPerformed
public boolean nguyenTo(int a){
    int dem = 0;
    for(int i=2;i<a;i++){
        if(a%i==0) dem++;
    }
    if(a==2) return true;
    if(a==1||a<0) return false;
    if(dem ==0 ) return true;
    else return false;
    
}
    
    private void btToDenSoNguyenToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToDenSoNguyenToActionPerformed
       jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
       ArrayList<Integer> arr = new ArrayList<Integer>();
      
      for(int i=0;i<(jList1.getModel().getSize());i++){
         int temp=Integer.parseInt(model.get(i).toString());
         if(nguyenTo(temp)){
           arr.add(i);
           
         }
      }
      int [] list = new int [arr.size()];
      
      for(int i=0;i<arr.size();i++){
          list[i]=arr.get(i);
      }
//        System.out.println(model.size());
      jList1.setSelectedIndices(list);
    }//GEN-LAST:event_btToDenSoNguyenToActionPerformed

    private void btSumListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumListActionPerformed
       int tong=0;
       for(int i=0;i<(jList1.getModel().getSize());i++){
         int temp=Integer.parseInt(model.get(i).toString());
         tong=tong+temp;
       }
       JOptionPane.showMessageDialog(null, "tong gia tri trong jlist la: "+tong);
    }//GEN-LAST:event_btSumListActionPerformed

    private void btXoaCacGiaTriToDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaCacGiaTriToDenActionPerformed
       //xoa cac gia tri dang to den
       for(int i=0;i<model.size();i++){
           model.removeElement(jList1.getSelectedValue());
       }
    }//GEN-LAST:event_btXoaCacGiaTriToDenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus btThoat feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THAO_TAC_TREN_JLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THAO_TAC_TREN_JLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THAO_TAC_TREN_JLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THAO_TAC_TREN_JLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THAO_TAC_TREN_JLIST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoToDen;
    private javax.swing.JButton btNhap;
    private javax.swing.JButton btSumList;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btToDenSoNguyenTo;
    private javax.swing.JButton btToSenSoLe;
    private javax.swing.JButton btToSenSochan;
    private javax.swing.JButton btXoaCacGiaTriToDen;
    private javax.swing.JCheckBox chSoAm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Integer> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfNhap;
    // End of variables declaration//GEN-END:variables
}
